version: '3'

volumes:
  pg_data:

services:
  db:
    image: postgres:13.10
    env_file: .env
    environment:
      POSTGRES_USER: Saeed
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: flask
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  backend:
    image: saeed12/my-dash-backend
    env_file: .env
    depends_on:
      - db
    links:
      - db:flask-db

  gateway:
    image: saeed12/my-dash-gateway
    ports:
      - 8000:80
